/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "trlcrbepukfgalsxepor"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRybGNyYmVwdWtmZ2Fsc3hlcG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNTY2NDQsImV4cCI6MjA4MDYzMjY0NH0.k12M03-Sb5sHP-LMNEiATAXUKWJLeoNtFh4mO-BT_a0"